version: 1
formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
handlers:
  file_handler:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: logs/etl_app.log
loggers:
  main_logger:
    level: DEBUG
    handlers: [file_handler]
    propagate: no
  data_cleaning_logger:
    level: DEBUG
    handlers: [file_handler]
    propagate: no
  transformations_logger:
    level: DEBUG
    handlers: [file_handler]
    propagate: no
  aggregations_logger:
    level: DEBUG
    handlers: [file_handler]
    propagate: no
  utils_logger:
    level: DEBUG
    handlers: [file_handler]
    propagate: no
root:
  level: WARNING
  handlers: [file_handler]
